"""
Accounts Service - Main Application

FastAPI application for Global Digital Bank Accounts Service.

Author: GDB Architecture Team
Version: 1.0.0
"""

from contextlib import asynccontextmanager
import logging
import sys
from pathlib import Path
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from fastapi.openapi.utils import get_openapi
from pathlib import Path
import sys

# Import JWT config setup (from Auth Service's shared security module)
# MUST BE DONE BEFORE IMPORTING APP MODULES THAT USE AUTH DEPENDENCIES
auth_service_path = str(Path(__file__).parent.parent.parent / "auth_service" / "app")
if auth_service_path not in sys.path:
    sys.path.insert(0, auth_service_path)

try:
    from security.auth_dependencies import set_jwt_config
except ImportError:
    # Fallback path
    auth_service_parent = str(Path(__file__).parent.parent.parent / "auth_service")
    if auth_service_parent not in sys.path:
        sys.path.insert(0, auth_service_parent)
    from app.security.auth_dependencies import set_jwt_config

from app.config.settings import settings
from app.config.logging import setup_logging
from app.database.db import initialize_db, close_db
from app.api import account_routes, internal_accounts

# Configure logging
logger = setup_logging()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Manage application lifecycle.
    
    Handles startup and shutdown events.
    """
    # Startup
    logger.info("🚀 Starting Accounts Service...")
    
    # Initialize JWT config for authorization
    try:
        set_jwt_config(
            secret_key=settings.jwt_secret_key,
            algorithm=settings.jwt_algorithm,
            disable_auth=settings.disable_auth,
        )
        logger.info("✅ JWT config initialized")
    except Exception as e:
        logger.error(f"Failed to initialize JWT config: {str(e)}")
        raise
    
    await initialize_db(
        str(settings.database_url),
        min_size=settings.min_db_pool_size,
        max_size=settings.max_db_pool_size
    )
    logger.info("✅ Database initialized")
    
    yield
    
    # Shutdown
    logger.info("🛑 Shutting down Accounts Service...")
    await close_db()
    logger.info("✅ Accounts Service stopped")


# Create FastAPI app
app = FastAPI(
    title=settings.app_name,
    description="Microservice for managing bank accounts",
    version=settings.app_version,
    openapi_url=f"{settings.api_prefix}/openapi.json",
    docs_url=f"{settings.api_prefix}/docs",
    redoc_url=f"{settings.api_prefix}/redoc",
    lifespan=lifespan
)

# Add OpenAPI security scheme for Bearer token
def custom_openapi():
    """Custom OpenAPI schema with Bearer token security."""
    if app.openapi_schema:
        return app.openapi_schema
    
    # Get the default OpenAPI schema generated by FastAPI
    openapi_schema = get_openapi(
        title=settings.app_name,
        version=settings.app_version,
        description="Microservice for managing bank accounts",
        routes=app.routes,
    )
    
    # Add Bearer token security scheme
    openapi_schema["components"]["securitySchemes"] = {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
            "description": "JWT Bearer token. Get from Auth Service /login endpoint",
        }
    }
    
    # Apply security to all endpoints
    openapi_schema["security"] = [{"Bearer": []}]
    
    app.openapi_schema = openapi_schema
    return app.openapi_schema

app.openapi = custom_openapi

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)(:\d+)?|https?://.*\.onrender\.com",
    allow_origins=settings.CORS_ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Add trusted host middleware
app.add_middleware(
    TrustedHostMiddleware,
    allowed_hosts=["localhost", "127.0.0.1", "*.gdb.local", "accounts-service", "gdb-accounts-service", "*"]
)


# Include routers
app.include_router(
    account_routes.router,
    prefix=settings.api_prefix,
    tags=["accounts"]
)

app.include_router(
    internal_accounts.router,
    prefix=f"{settings.api_prefix}/internal",
    tags=["internal"]
)


@app.get("/health", tags=["health"])
async def health_check():
    """
    Health check endpoint.
    
    Returns:
        dict: Service health status
    """
    return {
        "status": "healthy",
        "service": settings.app_name,
        "version": settings.app_version,
        "environment": settings.environment
    }


@app.get("/", tags=["root"])
async def root():
    """
    Root endpoint.
    
    Returns:
        dict: Service information
    """
    return {
        "service": settings.app_name,
        "version": settings.app_version,
        "docs": f"http://localhost:{settings.port}{settings.api_prefix}/docs"
    }


if __name__ == "__main__":
    import uvicorn
    
    uvicorn.run(
        "app.main:app",
        host=settings.host,
        port=settings.port,
        reload=settings.debug,
        log_level=settings.log_level.lower()
    )
